### ISSUE TITLE
Probleme mit dem "Meisterbogen"

### ISSUE THREAD

**Issue by Althalusdlg** [leo-schirmer/dsa4.1-mt1.7#1]
Moin,

exportierte Charaktere müssen erst in MapTool 1.7.0 geöffnet werden, dann Exportiert und danach dann in die neuste MapTool Version wieder Importiert werden.

Des weiteren gibt Probleme den Meisterbogen zu öffnen. Hier die Fehlermeldung dazu:

`Ungültige Bedingung in IF(getVisible(tName) == 1 && getLayer(tName) != "GM" && getLayer(tName) != "BACKGROUND" && getLayer(tName) != "OBJECT") Listenoption.       Anweisungsoptionen (falls vorhanden): if(getVisible(tName) == 1 && getLayer(tName) != "GM" && getLayer(tName) != "BACKGROUND" && getLayer(tName) != "OBJECT")       Anweisung: fTokenList = listAppend(fTokenList, tName, "%A0")
Fehlerspur: meisterbogenNSC1@Lib:macros2 <<< macroLink
    Ungültige Bedingung in IF(getVisible(tName) == 1) Listenoption.       Anweisungsoptionen (falls vorhanden): if(getVisible(tName) == 1)       Anweisung: fTokenList = listAppend(fTokenList, tName, "%A0")
Fehlerspur: meisterbogenSC2@Lib:macros2 <<< macroLink`

Edith sagt: Es wird MapTool 1.8.3 verwendet. :) Alle NSC Tokens können ansonsten ganz normal geöffnet werden als SL so das man ausschließen kann das es an den Tokens der NSC liegt.

Edith 2: Es wird auch die neuste Version des Exporters genutzt, also mit den Waffeneigenschaften für die WM und TP Berechnung.

**Comment by leo-schirmer** [comment]
Danke für die Rückmeldung. Ich hatte das Kampagnenfile für MapTool Version 1.7 umgebaut. Hatte mich gerade schon gewundert, warum ich den Fehler mit dem Meisterbogen nicht reproduzieren konnte.

Was passiert denn, wenn man Charaktere in der Heldensoftware exportiert und dann direkt in 1.8.3 importiert?

Geht ansonsten alles? Wenn es nur das ist, könnte ich das vielleicht fixen.

**Comment by Althalusdlg** [comment]
Gut die MapTool 1.7 ist ja offiziell mit allen vorhergehenden nun Obsolet aus Sicherheitsgründen. Auch wenn Sie immer noch Funktioniert falls man über IP Adresse sich verbindet. Deswegen sind wir auf die 1.8.3 umgestiegen.
Der Meisterbogen ist der wichtigste Bogen für uns, da man als SL so sehr schnell alle NSC durchschalten kann.

Was die Fehlermeldung angeht muss ich das zu Hause noch einmal ausprobieren. Melde mich da später dann noch mal und Berichte.

**Comment by leo-schirmer** [comment]
Ich habe gestern die aktuelle Version 1.8.4 installiert, konnte aber leider keinen der Fehler reproduzieren: Der Meisterbogen öffnet bei mir ohne "Murren" und auch einen Token konnte ich direkt importieren und nutzen. Kannst Du bitte noch mal genau schreiben, mit welchem File bei welchem Ablauf Fehler auftreten?

**Comment by Althalusdlg** [comment]
Konnte jetzt ein bisschen weiter Testen. Sorry hatte zu viel zu tun gehabt.
Das Problem scheinen meine Karten zu sein. Ich benutze andere Karten als die von Dir (also die beiden Aventurienkarten). Wenn die drin sind dann geht es nicht... sind sie rausgenommen geht es mit dem Meisterbogen.
Aus mir unerfindlichen Gründen haben diese Eigenschaftswerte und dadurch kommt wohl das Problem zustande. Muss ich die noch neu einfügen, evtl. klappt es dann.

**Comment by leo-schirmer** [comment]
Schick mir gern einen Link, wenn Du magst. Dann gucke ich mal. Weiß aber natürlich nicht, was da sonst so los ist auf den Karten.

**Comment by Althalusdlg** [comment]
So, Karten einmal alle neu eingefügt und nu läuft es wieder. Sehr Merkwürdig aber gut scheint gelöst zu sein jetzt.
Danke für deine Mühen. :)
